# We set the language to c because python isn't supported on the MacOS X nodes
# on Travis. However, the language ends up being irrelevant anyway, since we
# install Python ourselves using conda.
language: c

os:
    - linux

stage: Initial tests

# Setting sudo to false opts in to Travis-CI container-based builds.
sudo: false

# The apt packages below are needed for sphinx builds. A full list of
# packages that can be included can be found here:
# https://github.com/travis-ci/apt-package-whitelist/blob/master/ubuntu-precise
addons:
    apt:
        packages:
            - graphviz
            - texlive-latex-extra
            - dvipng

env:
    global:
        # The following versions are the 'default' for tests, unless
        # overridden underneath. They are defined here in order to save having
        # to repeat them for all configurations.
        - PYTHON_VERSION=3.6
        - NUMPY_VERSION=stable
        - ASTROPY_VERSION=stable
        - CONDA_CHANNELS='astropy-ci-extras astropy'
        - CONDA_DEPENDENCIES='Cython scipy scikit-image scikit-learn matplotlib'
        - CONDA_REQUIRED_DEPENDENCIES='Cython'
        - MAIN_CMD='python setup.py'
        - SETUP_CMD='test'
        - EVENT_TYPE='push pull_request'
        - SETUP_XVFB=True

        # PEP8 errors/warnings:
        # E101 - mix of tabs and spaces
        # W191 - use of tabs
        # W291 - trailing whitespace
        # W292 - no newline at end of file
        # W293 - trailing whitespace
        # W391 - blank line at end of file
        # E111 - 4 spaces per indentation level
        # E112 - 4 spaces per indentation level
        # E113 - 4 spaces per indentation level
        # E502 - the backslash is redundant between brackets
        # E722 - do not use bare except
        # E901 - SyntaxError or IndentationError
        # E902 - IOError
        - FLAKE8_OPT="--select=E101,W191,W291,W292,W293,W391,E111,E112,E113,E502,E722,E901,E902"

stages:
   - name: Initial tests
   - name: Comprehensive tests
   - name: Cron tests
     if: type = cron

matrix:
    # Don't wait for allowed failures
    fast_finish: true

    include:
        - env: PYTHON_VERSION=3.7 SETUP_CMD='egg_info'

        # Test with Astropy dev version and the latest Python
        - stage: Comprehensive tests
          env: ASTROPY_VERSION=development
               EVENT_TYPE='pull_request push cron'
               PIP_DEPENDENCIES='https://github.com/bsipocz/astropy/archive/testing_header_print_actual_helpers.zip'

install:
    - git clone git://github.com/astropy/ci-helpers.git
    - source ci-helpers/travis/setup_conda.sh

script:
   - $MAIN_CMD $SETUP_CMD

after_success:
    - if [[ $SETUP_CMD == *--coverage* ]]; then
          coveralls --rcfile='photutils/tests/coveragerc';
      fi
